In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("expert_data.csv")

In [12]:
df.head()

,time,RPC,RPF,RPT,RMC,RMF,RMT,RAC,RAF,RAT,...,imu_yaw,LAS,LMS,LPS,RAS,RMS,RPS,mantis_x,mantis_y,mantis_z
0,0.01,-0.592147,0.979155,-2.428651,-0.007853,0.620845,-2.371349,0.607853,0.979155,-2.428651,...,-3.135315,1.0,1.0,1.0,1.0,1.0,1.0,-0.001365,-0.037066,0.125893
1,0.02,-0.584302,0.976275,-2.427349,-0.015698,0.623725,-2.372651,0.615698,0.976275,-2.427349,...,-3.134274,0.0,0.0,0.0,0.0,0.0,0.0,-0.000696,-0.037043,0.122258
2,0.03,-0.576473,0.973220,-2.426021,-0.023527,0.626780,-2.373979,0.623527,0.973220,-2.426021,...,-3.133540,0.0,0.0,0.0,0.0,0.0,0.0,-0.000112,-0.038696,0.122968
3,0.04,-0.568667,0.969994,-2.424667,-0.031333,0.630006,-2.375333,0.631333,0.969994,-2.424667,...,-3.133319,0.0,0.0,0.0,0.0,0.0,0.0,-0.000043,-0.047006,0.123479
4,0.05,-0.560891,0.966601,-2.423289,-0.039109,0.633399,-2.376711,0.639109,0.966601,-2.423289,...,-3.132746,0.0,0.0,0.0,0.0,1.0,0.0,-0.000398,-0.053346,0.123886

Touch sensors are no longer used, so:

In [13]:
df_new = df.drop(columns=['LAS','LMS','LPS','RAS','RMS','RPS'])
df_new.head()

,time,RPC,RPF,RPT,RMC,RMF,RMT,RAC,RAF,RAT,...,LMT,LAC,LAF,LAT,imu_roll,imu_pitch,imu_yaw,mantis_x,mantis_y,mantis_z
0,0.01,-0.592147,0.979155,-2.428651,-0.007853,0.620845,-2.371349,0.607853,0.979155,-2.428651,...,-2.428651,-0.592147,0.620845,-2.371349,-0.000004,0.000084,-3.135315,-0.001365,-0.037066,0.125893
1,0.02,-0.584302,0.976275,-2.427349,-0.015698,0.623725,-2.372651,0.615698,0.976275,-2.427349,...,-2.427349,-0.584302,0.623725,-2.372651,0.000002,0.000043,-3.134274,-0.000696,-0.037043,0.122258
2,0.03,-0.576473,0.973220,-2.426021,-0.023527,0.626780,-2.373979,0.623527,0.973220,-2.426021,...,-2.426021,-0.576473,0.626780,-2.373979,0.000135,0.000066,-3.133540,-0.000112,-0.038696,0.122968
3,0.04,-0.568667,0.969994,-2.424667,-0.031333,0.630006,-2.375333,0.631333,0.969994,-2.424667,...,-2.424667,-0.568667,0.630006,-2.375333,0.001632,0.000068,-3.133319,-0.000043,-0.047006,0.123479
4,0.05,-0.560891,0.966601,-2.423289,-0.039109,0.633399,-2.376711,0.639109,0.966601,-2.423289,...,-2.423289,-0.560891,0.633399,-2.376711,0.002708,-0.000329,-3.132746,-0.000398,-0.053346,0.123886

In [15]:
df_new.to_csv("clean_expert.csv", index=False)